graduationArt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView
from mapapp.views import MapListView

urlpatterns = [
    path('', MapListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('maps/', include('mapapp.urls')),
    path('videos/', include('videoapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mapapp/urls.py
from django.urls import path

from mapapp.views import MapCreateView, MapDetailView, MapListView, MapUpdateView, MapDeleteView

app_name = 'mapapp'

urlpatterns = [
    path('list/', MapListView.as_view(), name='list'),

    path('create/', MapCreateView.as_view(), name='create'),
    path('detail/<int:pk>', MapDetailView.as_view(), name='detail'),
    path('update/<int:pk>', MapUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', MapDeleteView.as_view(), name='delete'),
]

mapapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Map(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='map', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='map/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

templates/snippets/card.html
<div>
    <img src="{{ article.image.url }}" alt="">
    <img src="{{ map.image.url }}" alt="">
</div>

templates/snippets/card_project.html
<div style="display: block; text-align: center;">
    <img src="{{ project.image.url }}" alt="">
    <h5 class="mt-2" style="font-family: 'NanumSquareB'">
        {{project.title | truncatechars:8}}
    </h5>
</div>

templates/snippets/list_fragment.html
{% load static %}

<style>

    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;

        border-radius: 1rem;
    }

    .container img {
        width: 100%;
        border-radius: 1rem;
    }

</style>
    {% if map_list %}
    <div class="container">
        {% for map in map_list %}
            <a href="{% url 'mapapp:detail' pk=map.pk %}">
                {% include 'snippets/card.html' with map=map %}
            </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
    <div class="text-center">
        <h1>No Map YET!</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center">
        <a href="{% url 'mapapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
            Create Map
        </a>
    </div>

templates/snippets/pagination.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"
       class="btn btn-secondary rounded-pill">
        {{ page_obj.previous_page_number }}
    </a>
    {% endif %}
    <a hred="?page={{ page_obj.number }}"
       class="btn btn-secondary rounded-pill activate">
        {{ page_obj.number }}
    </a>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"
       class="btn btn-secondary rounded-pill">
        {{ page_obj.next_page_number }}
    </a>
    {% endif %}
</div>